drop table if exists p_type1;
create table p_type1 (no int, pno char (150) );
drop table if exists p_type2;
create table p_type2 (no int, pno varchar (255) );
drop table if exists p_type3;
create table p_type3 (no int, pno varbinary (255));
drop table if exists p_type4;
create table p_type4 (no int, pno char (150) );
drop table if exists p_type5;
create table p_type5 (no int, pno varchar (255) );
drop table if exists p_type6;
create table p_type6 (no int, pno varbinary (255));
drop table if exists p_type7;
create table p_type7 (no int, pno char (150) );
drop table if exists p_type8;
create table p_type8 (no int, pno varchar (255) );
drop table if exists p_type9;
create table p_type9 (no int, pno varbinary (255));
drop table if exists p_type10;
create table p_type10 (no int, pno char (150) );
drop table if exists p_type11;
create table p_type11 (no int, pno varchar (255) );
drop table if exists p_type12;
create table p_type12 (no int, pno varbinary (255));
insert into p_type1 values(1, 'text_12345_!@#$%^');
insert into p_type2 values(1, 'text_12345_!@#$%^');
insert into p_type3 values(1, 'text_12345_!@#$%^');
insert into p_type4 values(1, 'text_12345_!@#$%^');
insert into p_type5 values(1, 'text_12345_!@#$%^');
insert into p_type6 values(1, 'text_12345_!@#$%^');
insert into p_type7 values(1, 'text_12345_!@#$%^');
insert into p_type8 values(1, 'text_12345_!@#$%^');
insert into p_type9 values(1, 'text_12345_!@#$%^');
insert into p_type10 values(1, 'text_12345_!@#$%^');
insert into p_type11 values(1, 'text_12345_!@#$%^');
insert into p_type12 values(1, 'text_12345_!@#$%^');
insert into p_type1 values(1, NULL);
insert into p_type2 values(1, NULL);
insert into p_type3 values(1, NULL);
insert into p_type4 values(1, NULL);
insert into p_type5 values(1, NULL);
insert into p_type6 values(1, NULL);
insert into p_type7 values(1, NULL);
insert into p_type8 values(1, NULL);
insert into p_type9 values(1, NULL);
insert into p_type10 values(1, NULL);
insert into p_type11 values(1, NULL);
insert into p_type12 values(1, NULL);
insert into p_type1 values(1, '');
insert into p_type2 values(1, '');
insert into p_type3 values(1, '');
insert into p_type4 values(1, '');
insert into p_type5 values(1, '');
insert into p_type6 values(1, '');
insert into p_type7 values(1, '');
insert into p_type8 values(1, '');
insert into p_type9 values(1, '');
insert into p_type10 values(1, '');
insert into p_type11 values(1, '');
insert into p_type12 values(1, '');

call mysql.damo_table_migration('test', 'p_type1');
call mysql.damo_table_migration('test', 'p_type2');
call mysql.damo_table_migration('test', 'p_type3');
call mysql.damo_table_migration('test', 'p_type4');
call mysql.damo_table_migration('test', 'p_type5');
call mysql.damo_table_migration('test', 'p_type6');
call mysql.damo_table_migration('test', 'p_type7');
call mysql.damo_table_migration('test', 'p_type8');
call mysql.damo_table_migration('test', 'p_type9');
call mysql.damo_table_migration('test', 'p_type10');
call mysql.damo_table_migration('test', 'p_type11');
call mysql.damo_table_migration('test', 'p_type12');
