drop table if exists type1;
drop table if exists type2;
drop table if exists type3;
drop table if exists type4;
drop table if exists type5;
drop table if exists type6;
drop table if exists type7;
drop table if exists type8;
drop table if exists type9;
drop table if exists type10;
drop table if exists type11;
drop table if exists type12;
drop table if exists type13;
drop table if exists type14;
drop table if exists type15;
drop table if exists type16;
drop table if exists type17;
drop table if exists type18;
drop table if exists type19;
drop table if exists type20;
drop table if exists type21;
drop table if exists type22;
drop table if exists type23;
drop table if exists type24;
drop table if exists type25;
drop table if exists type26;
drop table if exists type27;
drop table if exists type28;
drop table if exists type29;

create table type1 (no int, pno char (150) );
create table type2 (no int, pno varchar (255) );
create table type3 (no int, pno varbinary (255));
create table type4 (no int, pno tinyblob );
create table type5 (no int, pno blob );
create table type6 (no int, pno mediumblob );
create table type7 (no int, pno longblob );
create table type8 (no int, pno tinytext );
create table type9 (no int, pno text );
create table type10 (no int, pno mediumtext );
create table type11 (no int, pno longtext );
create table type12 (no int, pno tinyint);
create table type13 (no int, pno smallint );
create table type14 (no int, pno mediumint );
create table type15 (no int, pno int);
create table type16 (no int, pno bigint);
create table type17 (no int, pno date );
create table type18 (no int, pno time );
create table type19 (no int, pno datetime );
create table type20 (no int, pno timestamp );
create table type21 (no int, pno year );
create table type22 (no int, pno float );
create table type23 (no int, pno double );
create table type24 (no int, pno char (150) );
create table type25 (no int, pno text );
create table type26 (no int, pno int );
create table type27 (no int, pno blob );
create table type28 (no int, pno date );
create table type29 (no int, pno float );
insert into type1 values(1, 'text_12345_!@#$%^');
insert into type2 values(1, 'text_12345_!@#$%^');
insert into type3 values(1, 'text_12345_!@#$%^');
insert into type4 values(1, 'text_12345_!@#$%^');
insert into type5 values(1, 'text_12345_!@#$%^');
insert into type6 values(1, 'text_12345_!@#$%^');
insert into type7 values(1, 'text_12345_!@#$%^');
insert into type8 values(1, 'text_12345_!@#$%^');
insert into type9 values(1, 'text_12345_!@#$%^');
insert into type10 values(1, 'text_12345_!@#$%^');
insert into type11 values(1, 'text_12345_!@#$%^');
insert into type12 values(1, 123);
insert into type13 values(1, 124);
insert into type14 values(1, 125);
insert into type15 values(1, 126);
insert into type16 values(1, 127);
insert into type17 values(1, '1999-11-11');
insert into type18 values(1, '12:59:59');
insert into type19 values(1, '1994-03-11 23:59:59');
insert into type20 values(1, '2008-01-01 00:00:01');
insert into type21 values(1, '1999');
insert into type22 values(1, -3.402823466E+38);
insert into type23 values(1, -1.79769313486231517E+308);
insert into type24 values(1, 'text_12345_!@#$%^');
insert into type25 values(1, 'text_12345_!@#$%^');
insert into type26 values(1, 123);
insert into type27 values(1, 'text_12345_!@#$%^');
insert into type28 values(1, '1999-11-11');
insert into type29 values(1, -3.402823466E+38);
insert into type1 values(1, NULL);
insert into type2 values(1, NULL);
insert into type3 values(1, NULL);
insert into type4 values(1, NULL);
insert into type5 values(1, NULL);
insert into type6 values(1, NULL);
insert into type7 values(1, NULL);
insert into type8 values(1, NULL);
insert into type9 values(1, NULL);
insert into type10 values(1, NULL);
insert into type11 values(1, NULL);
insert into type12 values(1, NULL);
insert into type13 values(1, NULL);
insert into type14 values(1, NULL);
insert into type15 values(1, NULL);
insert into type16 values(1, NULL);
insert into type17 values(1, NULL);
insert into type18 values(1, NULL);
insert into type21 values(1, NULL);
insert into type22 values(1, NULL);
insert into type23 values(1, NULL);
insert into type24 values(1, NULL);
insert into type25 values(1, NULL);
insert into type26 values(1, NULL);
insert into type27 values(1, NULL);
insert into type28 values(1, NULL);
insert into type29 values(1, NULL);
insert into type1 values(1, '');
insert into type2 values(1, '');
insert into type3 values(1, '');
insert into type4 values(1, '');
insert into type5 values(1, '');
insert into type6 values(1, '');
insert into type7 values(1, '');
insert into type8 values(1, '');
insert into type9 values(1, '');
insert into type10 values(1, '');
insert into type11 values(1, '');
insert into type18 values(1, '');
insert into type24 values(1, '');
insert into type25 values(1, '');
insert into type27 values(1, '');


call mysql.damo_table_migration('test', 'type1');
call mysql.damo_table_migration('test', 'type2');
call mysql.damo_table_migration('test', 'type3');
call mysql.damo_table_migration('test', 'type4');
call mysql.damo_table_migration('test', 'type5');
call mysql.damo_table_migration('test', 'type6');
call mysql.damo_table_migration('test', 'type7');
call mysql.damo_table_migration('test', 'type8');
call mysql.damo_table_migration('test', 'type9');
call mysql.damo_table_migration('test', 'type10');
call mysql.damo_table_migration('test', 'type11');
call mysql.damo_table_migration('test', 'type12');
call mysql.damo_table_migration('test', 'type13');
call mysql.damo_table_migration('test', 'type14');
call mysql.damo_table_migration('test', 'type15');
call mysql.damo_table_migration('test', 'type16');
call mysql.damo_table_migration('test', 'type17');
call mysql.damo_table_migration('test', 'type18');
call mysql.damo_table_migration('test', 'type19');
call mysql.damo_table_migration('test', 'type20');
call mysql.damo_table_migration('test', 'type21');
call mysql.damo_table_migration('test', 'type22');
call mysql.damo_table_migration('test', 'type23');
call mysql.damo_table_migration('test', 'type24');
call mysql.damo_table_migration('test', 'type25');
call mysql.damo_table_migration('test', 'type26');
call mysql.damo_table_migration('test', 'type27');
call mysql.damo_table_migration('test', 'type28');
call mysql.damo_table_migration('test', 'type29');
